// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timetable.Infrastructure.Data;

#nullable disable

namespace ScheduleX.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260226160224_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Timetable.Core.Entities.BatchTemplateSnapshot", b =>
                {
                    b.Property<int>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SnapshotId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateJsonSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SnapshotId");

                    b.HasIndex("BatchId")
                        .IsUnique();

                    b.HasIndex("TemplateId");

                    b.ToTable("TblBatchTemplateSnapshot", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.BreakRule", b =>
                {
                    b.Property<int>("BreakRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BreakRuleId"));

                    b.Property<byte>("AfterLectureNo")
                        .HasColumnType("tinyint");

                    b.Property<int>("BreakDurationMin")
                        .HasColumnType("int");

                    b.Property<string>("BreakName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("BreakNo")
                        .HasColumnType("tinyint");

                    b.Property<int>("ConfigId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BreakRuleId");

                    b.HasIndex("ConfigId", "AfterLectureNo")
                        .IsUnique();

                    b.HasIndex("ConfigId", "BreakNo")
                        .IsUnique();

                    b.ToTable("TblBreakRule", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseCode")
                        .IsUnique()
                        .HasFilter("[CourseCode] IS NOT NULL");

                    b.HasIndex("DepartmentId");

                    b.ToTable("TblCourse", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("DepartmentId");

                    b.HasIndex("DepartmentCode")
                        .IsUnique()
                        .HasFilter("[DepartmentCode] IS NOT NULL");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("TblDepartment", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.Division", b =>
                {
                    b.Property<int>("DivisionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DivisionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("StudentStrength")
                        .HasColumnType("int");

                    b.HasKey("DivisionId");

                    b.HasIndex("SemesterId", "DivisionName")
                        .IsUnique();

                    b.ToTable("TblDivision", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.DivisionRoomAllocation", b =>
                {
                    b.Property<int>("AllocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AllocationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<bool>("IsFixed")
                        .HasColumnType("bit");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.HasKey("AllocationId");

                    b.HasIndex("DivisionId")
                        .IsUnique();

                    b.HasIndex("RoomId");

                    b.HasIndex("SemesterId");

                    b.ToTable("TblDivisionRoomAllocation", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.ExportHistory", b =>
                {
                    b.Property<int>("ExportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExportId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<byte>("ExportType")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("ExportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExportedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateSnapshotId")
                        .HasColumnType("int");

                    b.HasKey("ExportId");

                    b.HasIndex("BatchId");

                    b.HasIndex("ExportedByUserId");

                    b.HasIndex("TemplateSnapshotId");

                    b.ToTable("TblExportHistory", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.Faculty", b =>
                {
                    b.Property<int>("FacultyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacultyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FacultyCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("FacultyName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte?>("MaxLecturesPerDay")
                        .HasColumnType("tinyint");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("FacultyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("FacultyCode")
                        .IsUnique()
                        .HasFilter("[FacultyCode] IS NOT NULL");

                    b.ToTable("TblFaculty", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.FacultyAvailability", b =>
                {
                    b.Property<int>("AvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AvailabilityId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("AvailabilityId");

                    b.HasIndex("FacultyId");

                    b.ToTable("TblFacultyAvailability", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("RoomName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte>("RoomType")
                        .HasColumnType("tinyint");

                    b.HasKey("RoomId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoomName")
                        .IsUnique();

                    b.ToTable("TblRoom", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.ScheduleConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LectureDurationMin")
                        .HasColumnType("int");

                    b.Property<byte>("LecturesPerDay")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("WorkingDaysMask")
                        .HasColumnType("int");

                    b.HasKey("ConfigId");

                    b.HasIndex("CourseId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("TblScheduleConfig", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.Semester", b =>
                {
                    b.Property<int>("SemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SemesterId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte>("SemesterNo")
                        .HasColumnType("tinyint");

                    b.HasKey("SemesterId");

                    b.HasIndex("CourseId", "SemesterNo")
                        .IsUnique();

                    b.ToTable("TblSemester", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Credits")
                        .HasColumnType("tinyint");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsElective")
                        .HasColumnType("bit");

                    b.Property<byte>("SubjectCategory")
                        .HasColumnType("tinyint");

                    b.Property<string>("SubjectCode")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SubjectId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("SubjectCode")
                        .IsUnique()
                        .HasFilter("[SubjectCode] IS NOT NULL");

                    b.ToTable("TblSubject", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.SubjectOffering", b =>
                {
                    b.Property<int>("OfferingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacultyId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte?>("PracticalBlockSize")
                        .HasColumnType("tinyint");

                    b.Property<byte>("PracticalLecturesPerWeek")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("PreferredRoomType")
                        .HasColumnType("tinyint");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<byte>("TheoryLecturesPerWeek")
                        .HasColumnType("tinyint");

                    b.HasKey("OfferingId");

                    b.HasIndex("FacultyId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("SemesterId", "SubjectId")
                        .IsUnique();

                    b.ToTable("TblSubjectOffering", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.TimeSlot", b =>
                {
                    b.Property<int>("TimeSlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeSlotId"));

                    b.Property<int?>("BreakRuleId")
                        .HasColumnType("int");

                    b.Property<int>("ConfigId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<byte>("SlotNo")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SlotType")
                        .HasColumnType("tinyint");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("TimeSlotId");

                    b.HasIndex("BreakRuleId");

                    b.HasIndex("ConfigId", "SlotNo")
                        .IsUnique();

                    b.ToTable("TblTimeSlot", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.TimeTableBatch", b =>
                {
                    b.Property<int>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchId"));

                    b.Property<int>("ConfigId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActiveVersion")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("ParentBatchId")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("BatchId");

                    b.HasIndex("ConfigId");

                    b.HasIndex("CourseId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ParentBatchId");

                    b.HasIndex("TemplateId");

                    b.ToTable("TblTimeTableBatch", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.TimeTableBatchSemester", b =>
                {
                    b.Property<int>("BatchSemesterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BatchSemesterId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.HasKey("BatchSemesterId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("BatchId", "SemesterId")
                        .IsUnique();

                    b.ToTable("TblTimeTableBatchSemester", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.TimeTableEntry", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntryId"));

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<Guid?>("BlockId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("BlockPart")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<int>("DivisionId")
                        .HasColumnType("int");

                    b.Property<byte>("EntryType")
                        .HasColumnType("tinyint");

                    b.Property<int?>("OfferingId")
                        .HasColumnType("int");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("int");

                    b.HasKey("EntryId");

                    b.HasIndex("DivisionId");

                    b.HasIndex("OfferingId");

                    b.HasIndex("RoomId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("TimeSlotId");

                    b.HasIndex("BatchId", "DivisionId", "DayOfWeek", "TimeSlotId")
                        .IsUnique();

                    b.HasIndex("BatchId", "RoomId", "DayOfWeek", "TimeSlotId")
                        .IsUnique()
                        .HasFilter("[RoomId] IS NOT NULL");

                    b.ToTable("TblTimeTableEntry", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.TimeTableEntryHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("BatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("EntryId")
                        .HasColumnType("int");

                    b.Property<string>("NewDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldDataJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HistoryId");

                    b.HasIndex("BatchId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("EntryId");

                    b.ToTable("TblTimeTableEntryHistory", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.TimeTableTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<byte>("LayoutType")
                        .HasColumnType("tinyint");

                    b.Property<string>("TemplateJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TemplateId");

                    b.HasIndex("TemplateName")
                        .IsUnique();

                    b.ToTable("TblTimeTableTemplate", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<byte>("Role")
                        .HasColumnType("tinyint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("TblUser", (string)null);
                });

            modelBuilder.Entity("Timetable.Core.Entities.BatchTemplateSnapshot", b =>
                {
                    b.HasOne("Timetable.Core.Entities.TimeTableBatch", "TimeTableBatch")
                        .WithOne("BatchTemplateSnapshot")
                        .HasForeignKey("Timetable.Core.Entities.BatchTemplateSnapshot", "BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.TimeTableTemplate", "TimeTableTemplate")
                        .WithMany("TemplateSnapshots")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TimeTableBatch");

                    b.Navigation("TimeTableTemplate");
                });

            modelBuilder.Entity("Timetable.Core.Entities.BreakRule", b =>
                {
                    b.HasOne("Timetable.Core.Entities.ScheduleConfig", "ScheduleConfig")
                        .WithMany("BreakRules")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduleConfig");
                });

            modelBuilder.Entity("Timetable.Core.Entities.Course", b =>
                {
                    b.HasOne("Timetable.Core.Entities.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Timetable.Core.Entities.Division", b =>
                {
                    b.HasOne("Timetable.Core.Entities.Semester", "Semester")
                        .WithMany("Divisions")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Timetable.Core.Entities.DivisionRoomAllocation", b =>
                {
                    b.HasOne("Timetable.Core.Entities.Division", "Division")
                        .WithMany("DivisionRoomAllocations")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.Room", "Room")
                        .WithMany("DivisionRoomAllocations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.Semester", "Semester")
                        .WithMany("DivisionRoomAllocations")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Room");

                    b.Navigation("Semester");
                });

            modelBuilder.Entity("Timetable.Core.Entities.ExportHistory", b =>
                {
                    b.HasOne("Timetable.Core.Entities.TimeTableBatch", "TimeTableBatch")
                        .WithMany("ExportHistories")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.User", "ExportedByUser")
                        .WithMany("ExportHistories")
                        .HasForeignKey("ExportedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.BatchTemplateSnapshot", "BatchTemplateSnapshot")
                        .WithMany()
                        .HasForeignKey("TemplateSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BatchTemplateSnapshot");

                    b.Navigation("ExportedByUser");

                    b.Navigation("TimeTableBatch");
                });

            modelBuilder.Entity("Timetable.Core.Entities.Faculty", b =>
                {
                    b.HasOne("Timetable.Core.Entities.Department", "Department")
                        .WithMany("Faculties")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Timetable.Core.Entities.FacultyAvailability", b =>
                {
                    b.HasOne("Timetable.Core.Entities.Faculty", "Faculty")
                        .WithMany("FacultyAvailabilities")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faculty");
                });

            modelBuilder.Entity("Timetable.Core.Entities.Room", b =>
                {
                    b.HasOne("Timetable.Core.Entities.Department", "Department")
                        .WithMany("Rooms")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Timetable.Core.Entities.ScheduleConfig", b =>
                {
                    b.HasOne("Timetable.Core.Entities.Course", "Course")
                        .WithMany("ScheduleConfigs")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Timetable.Core.Entities.Department", "Department")
                        .WithMany("ScheduleConfigs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Timetable.Core.Entities.Semester", b =>
                {
                    b.HasOne("Timetable.Core.Entities.Course", "Course")
                        .WithMany("Semesters")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Timetable.Core.Entities.Subject", b =>
                {
                    b.HasOne("Timetable.Core.Entities.Department", "Department")
                        .WithMany("Subjects")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Timetable.Core.Entities.SubjectOffering", b =>
                {
                    b.HasOne("Timetable.Core.Entities.Faculty", "Faculty")
                        .WithMany("SubjectOfferings")
                        .HasForeignKey("FacultyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.Semester", "Semester")
                        .WithMany("SubjectOfferings")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.Subject", "Subject")
                        .WithMany("SubjectOfferings")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Faculty");

                    b.Navigation("Semester");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Timetable.Core.Entities.TimeSlot", b =>
                {
                    b.HasOne("Timetable.Core.Entities.BreakRule", "BreakRule")
                        .WithMany("TimeSlots")
                        .HasForeignKey("BreakRuleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Timetable.Core.Entities.ScheduleConfig", "ScheduleConfig")
                        .WithMany("TimeSlots")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BreakRule");

                    b.Navigation("ScheduleConfig");
                });

            modelBuilder.Entity("Timetable.Core.Entities.TimeTableBatch", b =>
                {
                    b.HasOne("Timetable.Core.Entities.ScheduleConfig", "ScheduleConfig")
                        .WithMany("TimeTableBatches")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.Course", "Course")
                        .WithMany("TimeTableBatches")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.User", "CreatedByUser")
                        .WithMany("CreatedBatches")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.Department", "Department")
                        .WithMany("TimeTableBatches")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.TimeTableBatch", "ParentBatch")
                        .WithMany()
                        .HasForeignKey("ParentBatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Timetable.Core.Entities.TimeTableTemplate", "TimeTableTemplate")
                        .WithMany("TimeTableBatches")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Department");

                    b.Navigation("ParentBatch");

                    b.Navigation("ScheduleConfig");

                    b.Navigation("TimeTableTemplate");
                });

            modelBuilder.Entity("Timetable.Core.Entities.TimeTableBatchSemester", b =>
                {
                    b.HasOne("Timetable.Core.Entities.TimeTableBatch", "TimeTableBatch")
                        .WithMany("BatchSemesters")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.Semester", "Semester")
                        .WithMany("BatchSemesters")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Semester");

                    b.Navigation("TimeTableBatch");
                });

            modelBuilder.Entity("Timetable.Core.Entities.TimeTableEntry", b =>
                {
                    b.HasOne("Timetable.Core.Entities.TimeTableBatch", "TimeTableBatch")
                        .WithMany("TimeTableEntries")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.Division", "Division")
                        .WithMany("TimeTableEntries")
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.SubjectOffering", "SubjectOffering")
                        .WithMany("TimeTableEntries")
                        .HasForeignKey("OfferingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Timetable.Core.Entities.Room", "Room")
                        .WithMany("TimeTableEntries")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Timetable.Core.Entities.Semester", "Semester")
                        .WithMany("TimeTableEntries")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.TimeSlot", "TimeSlot")
                        .WithMany("TimeTableEntries")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Division");

                    b.Navigation("Room");

                    b.Navigation("Semester");

                    b.Navigation("SubjectOffering");

                    b.Navigation("TimeSlot");

                    b.Navigation("TimeTableBatch");
                });

            modelBuilder.Entity("Timetable.Core.Entities.TimeTableEntryHistory", b =>
                {
                    b.HasOne("Timetable.Core.Entities.TimeTableBatch", "TimeTableBatch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.User", "ChangedByUser")
                        .WithMany("TimeTableEntryHistories")
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Timetable.Core.Entities.TimeTableEntry", "TimeTableEntry")
                        .WithMany("Histories")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("TimeTableBatch");

                    b.Navigation("TimeTableEntry");
                });

            modelBuilder.Entity("Timetable.Core.Entities.User", b =>
                {
                    b.HasOne("Timetable.Core.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Timetable.Core.Entities.BreakRule", b =>
                {
                    b.Navigation("TimeSlots");
                });

            modelBuilder.Entity("Timetable.Core.Entities.Course", b =>
                {
                    b.Navigation("ScheduleConfigs");

                    b.Navigation("Semesters");

                    b.Navigation("TimeTableBatches");
                });

            modelBuilder.Entity("Timetable.Core.Entities.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Faculties");

                    b.Navigation("Rooms");

                    b.Navigation("ScheduleConfigs");

                    b.Navigation("Subjects");

                    b.Navigation("TimeTableBatches");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Timetable.Core.Entities.Division", b =>
                {
                    b.Navigation("DivisionRoomAllocations");

                    b.Navigation("TimeTableEntries");
                });

            modelBuilder.Entity("Timetable.Core.Entities.Faculty", b =>
                {
                    b.Navigation("FacultyAvailabilities");

                    b.Navigation("SubjectOfferings");
                });

            modelBuilder.Entity("Timetable.Core.Entities.Room", b =>
                {
                    b.Navigation("DivisionRoomAllocations");

                    b.Navigation("TimeTableEntries");
                });

            modelBuilder.Entity("Timetable.Core.Entities.ScheduleConfig", b =>
                {
                    b.Navigation("BreakRules");

                    b.Navigation("TimeSlots");

                    b.Navigation("TimeTableBatches");
                });

            modelBuilder.Entity("Timetable.Core.Entities.Semester", b =>
                {
                    b.Navigation("BatchSemesters");

                    b.Navigation("DivisionRoomAllocations");

                    b.Navigation("Divisions");

                    b.Navigation("SubjectOfferings");

                    b.Navigation("TimeTableEntries");
                });

            modelBuilder.Entity("Timetable.Core.Entities.Subject", b =>
                {
                    b.Navigation("SubjectOfferings");
                });

            modelBuilder.Entity("Timetable.Core.Entities.SubjectOffering", b =>
                {
                    b.Navigation("TimeTableEntries");
                });

            modelBuilder.Entity("Timetable.Core.Entities.TimeSlot", b =>
                {
                    b.Navigation("TimeTableEntries");
                });

            modelBuilder.Entity("Timetable.Core.Entities.TimeTableBatch", b =>
                {
                    b.Navigation("BatchSemesters");

                    b.Navigation("BatchTemplateSnapshot");

                    b.Navigation("ExportHistories");

                    b.Navigation("TimeTableEntries");
                });

            modelBuilder.Entity("Timetable.Core.Entities.TimeTableEntry", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("Timetable.Core.Entities.TimeTableTemplate", b =>
                {
                    b.Navigation("TemplateSnapshots");

                    b.Navigation("TimeTableBatches");
                });

            modelBuilder.Entity("Timetable.Core.Entities.User", b =>
                {
                    b.Navigation("CreatedBatches");

                    b.Navigation("ExportHistories");

                    b.Navigation("TimeTableEntryHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
